services:
  nginx:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './static_files:/usr/share/nginx/html'
      - './media:/usr/share/nginx/html/media'
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Makes host.docker.internal work on Linux
